name: Build and Push Docker Image

# Workflow ini akan berjalan setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

# Variabel lingkungan untuk workflow ini.
# DOCKER_USERNAME dan DOCKER_PASSWORD diambil dari GitHub Secrets.
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE: kzrjnn/uas-asj

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Runner GitHub akan menggunakan mesin virtual Ubuntu terbaru

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Langkah ini mengambil kode dari repositori GitHub

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Menggunakan action untuk login ke Docker Hub
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        # Perintah untuk membangun image Docker dari Dockerfile di root proyek
        # Tag image dengan 'latest'
        run: docker build -t ${{ env.DOCKER_IMAGE }}:latest .

      - name: Push Docker image
        # Mendorong image yang sudah dibangun ke Docker Hub
        run: docker push ${{ env.DOCKER_IMAGE }}:latest